/* CRT portions adapted from Timothy Lottes' PUBLIC DOMAIN CRT STYLED SCAN-LINE SHADER.
 * Reference: https://github.com/stenzek/duckstation/blob/master/data/resources/shaders/crt-lottes.glsl
 * Reference blob: 2385c68e2cc183383aff6a34b6a2c53a7d3d2ec4
 * Original permission: "Please take and use, change, or whatever."
 * The original public-domain grant applies to the CRT algorithm.
 * Other filters and integration: GPL-2.0-or-later, as the surrounding Yabause code.
 * 4 = CRT-Lottes, 5 = CRT-Lottes without bloom, 6 = LCD, 7 = sharp bilinear, 8 = sharpen.
 */
#ifndef YGL_DISPLAY_FILTERS_H
#define YGL_DISPLAY_FILTERS_H
static const char display_filter_vertex[] =
"out vec2 vTexCoord;\n"
"void main() {\n"
"    vec2 p = vec2(float((gl_VertexID << 1) & 2), float(gl_VertexID & 2));\n"
"    vTexCoord = p;\n"
"    gl_Position = vec4(p * 2.0 - 1.0, 0.0, 1.0);\n"
"}\n";

static const char display_filter_fragment[] =
"#ifdef GL_ES\n"
"precision highp float;\n"
"precision highp int;\n"
"#endif\n"
"in vec2 vTexCoord;\n"
"uniform sampler2D uSource;\n"
"uniform vec2 uTextureSize;\n"
"uniform vec2 uNativeSize;\n"
"uniform vec2 uOutputSize;\n"
"uniform int uRotate;\n"
"out vec4 fragColor;\n"
"vec4 sampleSource(vec2 uv) {\n"
"    if (uRotate != 0) uv = vec2(uv.y, 1.0 - uv.x);\n"
"    return texture(uSource, uv);\n"
"}\n"
"\n"
"// Timothy Lottes' public-domain CRT filter, adapted to the Saturn framebuffer.\n"
"#if FILTER_MODE == 4 || FILTER_MODE == 5\n"
"vec2 distToPixel(vec2 p) { return 0.5 - fract(p * uNativeSize); }\n"
"vec3 fetchPixel(vec2 p, vec2 offset) {\n"
"    vec2 uv = (floor(p * uNativeSize + offset) + 0.5) / uNativeSize;\n"
"    if (any(lessThan(uv, vec2(0.0))) || any(greaterThan(uv, vec2(1.0))))\n"
"        return vec3(0.0);\n"
"    return pow(max(sampleSource(uv).rgb, vec3(0.0)), vec3(2.2));\n"
"}\n"
"float gauss(float d, float hardness) { return exp2(hardness * d * d); }\n"
"vec3 horz3(vec2 p, float row) {\n"
"    float d = distToPixel(p).x;\n"
"    float a = gauss(d - 1.0, -3.0), b = gauss(d, -3.0), c = gauss(d + 1.0, -3.0);\n"
"    return (fetchPixel(p, vec2(-1.0, row)) * a + fetchPixel(p, vec2(0.0, row)) * b\n"
"        + fetchPixel(p, vec2(1.0, row)) * c) / (a + b + c);\n"
"}\n"
"vec3 horz5(vec2 p, float row) {\n"
"    float d = distToPixel(p).x;\n"
"    vec3 sum = vec3(0.0);\n"
"    float total = 0.0;\n"
"    for (int x = -2; x <= 2; ++x) {\n"
"        float w = gauss(d + float(x), -3.0);\n"
"        sum += fetchPixel(p, vec2(float(x), row)) * w;\n"
"        total += w;\n"
"    }\n"
"    return sum / total;\n"
"}\n"
"#if FILTER_MODE == 4\n"
"vec3 horz7(vec2 p, float row) {\n"
"    float d = distToPixel(p).x;\n"
"    vec3 sum = vec3(0.0);\n"
"    float total = 0.0;\n"
"    for (int x = -3; x <= 3; ++x) {\n"
"        float w = gauss(d + float(x), -1.5);\n"
"        sum += fetchPixel(p, vec2(float(x), row)) * w;\n"
"        total += w;\n"
"    }\n"
"    return sum / total;\n"
"}\n"
"vec3 bloom(vec2 p) {\n"
"    float d = distToPixel(p).y;\n"
"    return horz5(p, -2.0) * gauss(d - 2.0, -2.0)\n"
"         + horz7(p, -1.0) * gauss(d - 1.0, -2.0)\n"
"         + horz7(p, 0.0) * gauss(d, -2.0)\n"
"         + horz7(p, 1.0) * gauss(d + 1.0, -2.0)\n"
"         + horz5(p, 2.0) * gauss(d + 2.0, -2.0);\n"
"}\n"
"#endif\n"
"vec3 lottes(vec2 uv) {\n"
"    vec2 p = uv * 2.0 - 1.0;\n"
"    p *= vec2(1.0 + p.y * p.y * 0.031, 1.0 + p.x * p.x * 0.041);\n"
"    p = p * 0.5 + 0.5;\n"
"    if (any(lessThan(p, vec2(0.0))) || any(greaterThan(p, vec2(1.0))))\n"
"        return vec3(0.0);\n"
"    float d = distToPixel(p).y;\n"
"    vec3 color = horz3(p, -1.0) * gauss(d - 1.0, -8.0)\n"
"               + horz5(p, 0.0) * gauss(d, -8.0)\n"
"               + horz3(p, 1.0) * gauss(d + 1.0, -8.0);\n"
"#if FILTER_MODE == 4\n"
"    color += bloom(p) * 0.15;\n"
"#endif\n"
"    // Stretched VGA shadow mask, anchored to output pixels, independent of viewport origin.\n"
"    vec2 pixel = floor(uv * uOutputSize);\n"
"    float stripe = fract((pixel.x + pixel.y * 3.0) / 6.0);\n"
"    vec3 mask = vec3(0.5);\n"
"    if (stripe < 1.0 / 3.0) mask.r = 1.5;\n"
"    else if (stripe < 2.0 / 3.0) mask.g = 1.5;\n"
"    else mask.b = 1.5;\n"
"    return pow(max(color * mask, vec3(0.0)), vec3(1.0 / 2.2));\n"
"}\n"
"#endif\n"
"\n"
"#if FILTER_MODE == 7\n"
"vec3 sharpBilinear(vec2 uv) {\n"
"    // Interpolate between native pixel centres only near their boundaries.\n"
"    vec2 scale = max(floor(uOutputSize / uNativeSize), vec2(1.0));\n"
"    vec2 p = uv * uNativeSize - 0.5;\n"
"    vec2 base = floor(p);\n"
"    vec2 f = clamp((fract(p) - 0.5) * scale + 0.5, 0.0, 1.0);\n"
"    vec2 a = (base + 0.5) / uNativeSize;\n"
"    vec2 stepSize = 1.0 / uNativeSize;\n"
"    vec3 top = mix(sampleSource(a).rgb, sampleSource(a + vec2(stepSize.x, 0.0)).rgb, f.x);\n"
"    vec3 bottom = mix(sampleSource(a + vec2(0.0, stepSize.y)).rgb,\n"
"        sampleSource(a + stepSize).rgb, f.x);\n"
"    return mix(top, bottom, f.y);\n"
"}\n"
"#endif\n"
"\n"
"void main() {\n"
"    vec2 uv = vTexCoord;\n"
"    vec3 color;\n"
"#if FILTER_MODE == 4 || FILTER_MODE == 5\n"
"    color = lottes(uv);\n"
"#elif FILTER_MODE == 6\n"
"    vec2 pixel = uv * uNativeSize;\n"
"    vec2 edge = abs(fract(pixel) - 0.5);\n"
"    vec2 scale = uOutputSize / uNativeSize;\n"
"    // Fade the grid out near 1:1 or downscaled output to prevent moire.\n"
"    float amount = smoothstep(1.0, 3.0, min(scale.x, scale.y));\n"
"    float grid = smoothstep(0.34, 0.50, max(edge.x, edge.y));\n"
"    color = sampleSource((floor(pixel) + 0.5) / uNativeSize).rgb;\n"
"    color *= 1.0 - 0.35 * grid * amount;\n"
"#elif FILTER_MODE == 7\n"
"    color = sharpBilinear(uv);\n"
"#elif FILTER_MODE == 8\n"
"    vec2 stepSize = 1.0 / uTextureSize;\n"
"    vec3 centre = sampleSource(uv).rgb;\n"
"    vec3 north = sampleSource(uv + vec2(0.0, stepSize.y)).rgb;\n"
"    vec3 south = sampleSource(uv - vec2(0.0, stepSize.y)).rgb;\n"
"    vec3 east = sampleSource(uv + vec2(stepSize.x, 0.0)).rgb;\n"
"    vec3 west = sampleSource(uv - vec2(stepSize.x, 0.0)).rgb;\n"
"    vec3 low = min(centre, min(min(north, south), min(east, west)));\n"
"    vec3 high = max(centre, max(max(north, south), max(east, west)));\n"
"    color = clamp(centre + 0.35 * (centre - (north + south + east + west) * 0.25), low, high);\n"
"#else\n"
"    color = sampleSource(uv).rgb;\n"
"#endif\n"
"    fragColor = vec4(clamp(color, 0.0, 1.0), 1.0);\n"
"}\n";
#endif

