#!/usr/bin/env python3
"""Embed Roc-Y's three Dot-clear passes with the original preset defaults.

Run after changing the vendored source. Generated GLSL has no runtime file IO.
The third-party algorithm retains its own notice; see phosphor-dot-v3.3/NOTICE.md.
"""
import json
from pathlib import Path
import re

root = Path(__file__).resolve().parent
source = root / "phosphor-dot-v3.3"
names = ["color-adjust", "phosphor-dot", "rgb-offset"]
texts = [(source / "passes" / (name + ".glsl")).read_text() for name in names]
defaults = {}
for text in texts:
    defaults.update(re.findall(r'#pragma parameter (\w+) "[^"]*" ([\d.-]+)', text))
defaults.update(re.findall(r'^(\w+) = "([\d.-]+)"', (source / "Dot-clear.glslp").read_text(), re.M))
output = ["/* Generated by generate_dot_clear.py. Roc-Y's shader notice is preserved below. */",
          "#ifndef YGL_DOT_CLEAR_SHADERS_H", "#define YGL_DOT_CLEAR_SHADERS_H"]
for index, original in enumerate(texts):
    # Keep fragment compatibility definitions, strip the original vertex stage.
    before = original.split("#if defined(VERTEX)")[0]
    text = "#ifdef GL_ES\nprecision highp float;\nprecision highp int;\n#endif\n" + before + original.split("#elif defined(FRAGMENT)", 1)[1].rsplit("#endif", 1)[0]
    text = re.sub(r'^#pragma.*\n', '', text, flags=re.M)
    text = text.replace("COMPAT_VARYING vec4 TEX0;", "in vec2 vTexCoord;")
    text = text.replace("#define vTexCoord TEX0.xy", "")
    # Parameters are fixed to this preset, including defaults absent from its UI list.
    text = re.sub(r'uniform COMPAT_PRECISION float (\w+);',
                  lambda m: 'const float %s = %s;' % (m[1], defaults.get(m[1], '0.0')), text)
    text = text.replace("#define COMPAT_PRECISION mediump", "#define COMPAT_PRECISION highp")
    # Defined nearest sampling for LINEAR_X/Y == 0 (the upstream divides by zero).
    text = text.replace("fract(pix_co+blur*0.5)/blur", "fract(pix_co+blur*0.5)/max(blur,vec2(1e-6))")
    text = text.replace("smoothstep(1000.0, 0.0, temperature)", "(1.0-smoothstep(0.0, 1000.0, temperature))")
    # GLES 3.0 lacks clamp-to-border. Emulate black borders without changing sampler state.
    pos = text.index("// compatibility #defines")
    wrapper = """
uniform int uRotate;
vec4 dotSample(sampler2D source, vec2 uv) {
    if (uRotate != 0) uv = vec2(uv.y, 1.0 - uv.x);
    if (any(lessThan(uv, vec2(0.0))) || any(greaterThan(uv, vec2(1.0))))
        return vec4(0.0, 0.0, 0.0, 1.0);
    return texture(source, uv);
}
"""
    text = text[:pos] + wrapper + text[pos:]
    text = text.replace("COMPAT_TEXTURE(Source,", "dotSample(Source,")
    # Upstream leaves alpha undefined; game presentation is always opaque.
    text = text.replace("void main()", "void dotMain()")
    text += "\nvoid main() { dotMain(); FragColor.a = 1.0; }\n"
    output.append("static const char dot_clear_fragment_%d[] =" % index)
    output.extend(json.dumps(line + "\n", ensure_ascii=True) for line in text.splitlines())
    output.append(";")
output.extend(["static const char *const dot_clear_fragments[] = {",
               "    dot_clear_fragment_0, dot_clear_fragment_1, dot_clear_fragment_2 };", "#endif", ""])
(root / "DotClearShaders.h").write_text("\n".join(output))
